version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    volumes:
      - it_bee:/var/opt/mssql
    environment:
      SA_PASSWORD: "Nam09189921"
      ACCEPT_EULA: "Y"
    restart: on-failure
    networks:
      - sql_network

networks:
  sql_network:
volumes:
  it_bee:
